ALTER TABLE auctions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS lot_number VARCHAR(50);
