ALTER TABLE auctions
  ALTER COLUMN start_time TYPE TIMESTAMPTZ USING start_time AT TIME ZONE 'UTC',
  ALTER COLUMN end_time TYPE TIMESTAMPTZ USING end_time AT TIME ZONE 'UTC',
  ALTER COLUMN payment_deadline TYPE TIMESTAMPTZ USING payment_deadline AT TIME ZONE 'UTC',
  ALTER COLUMN ended_at TYPE TIMESTAMPTZ USING ended_at AT TIME ZONE 'UTC',
  ALTER COLUMN settled_at TYPE TIMESTAMPTZ USING settled_at AT TIME ZONE 'UTC';

ALTER TABLE bids
  ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

UPDATE auctions
SET status = CASE
  WHEN CURRENT_TIMESTAMP < start_time THEN 'SCHEDULED'
  WHEN CURRENT_TIMESTAMP < end_time THEN 'LIVE'
  ELSE 'ENDED'
END
WHERE status IN ('SCHEDULED', 'LIVE', 'ENDED');
